all:
  hosts:
    focal:
      ansible_host: "{{ ubuntu_host }}"
  
  vars:
    ansible_user: "{{ ubuntu_user }}"
    ansible_private_key_file: "{{ ubuntu_private_key_file }}"
    ansible_port: "{{ ubuntu_port }}"
    ansible_python_interpreter: "{{ ansible_python_interpreter }}"