- block:
    - name: ADD SOURCES FILE
      template:
        src: sources.list
        dest: /etc/apt/sources.list
        owner: "root"
        group: "root"
        mode: "0644"

    - name: CUSTOM BASHRC
      template:
        src: bashrc
        dest: .bashrc
        owner: "{{ ubuntu_user }}"
        group: "{{ ubuntu_user }}"
        mode: "0644"

## SPOTIFY MUSIC
    - name: SPOTIFY GPG
      apt_key:
        url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
        state: present

    - name: SPOTIFY
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        filename: spotify
        state: present

## TYPORA MARKDOWN
    - name: TYPORA KEY
      apt_key:
        url: https://typora.io/linux/public-key.asc
        state: present

    - name: TYPORA
      apt_repository:
        repo: deb https://typora.io/linux ./
        filename: typora
        state: present

## VSCODE IDE
    - name: VSCODE KEY
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: VSCODE
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
        filename: vscode
        state: present

## NODEJS AND YARN
    - name: NODEJS KEY
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        keyring: /usr/share/keyrings/nodesource.gpg
        state: present

    - name: NODEJS
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x {{ ubuntu_name }} main
        filename: nodesource
        state: present

    - name: NODEJS SRC
      apt_repository:
        repo: deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x {{ ubuntu_name }} main
        filename: nodesource
        state: present

    - name: YARN KEY
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        keyring: /usr/share/keyrings/yarnkey.gpg
        state: present

    - name: YARN
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main
        filename: yarn
        state: present

## DATABASES
    - name: POSTGRESQL KEY
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: POSTGESQL
      apt_repository:
        repo: deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt {{ ubuntu_name }}-pgdg main
        filename: pgdg
        state: present

## CONTAINERS
    - name: DOCKER GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: DOCKER CE
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_name }} stable
        filename: docker-ce
        state: present

## KUBERNETES CLIENTS
    - name: KUBECTL KEY
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        state: present

    - name: KUBECTL
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        filename: kubectl
        state: present

## HASHICORP TOOLS
    - name: HASHICORP KEY
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: HASHICORP
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ubuntu_name }} main
        filename: hashicorp
        state: present

## AZURE TOOLS
    - name: AZURE-CLI KEY
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
        state: present

    - name: AZURE-CLI
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ubuntu_name }} main
        filename: azure-cli
        state: present

## ULAUNCHER TOOL
    - name: PPA ULAUNCHER
      apt_repository:
        repo: ppa:agornostal/ulauncher
        codename: "{{ ubuntu_name }}"

## BRAVE BROWSER
    - name: BRAVE BROWSER KEY
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        state: present

    - name: BRAVE BROWSER
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
        filename: brave-browser
        state: present

## DISABLED REPOSITORIES
    #  - name: MARIADB KEY
    #    apt_key:
    #      url: https://mariadb.org/mariadb_release_signing_key.asc
    #      state: present
    #
    #  - name: MARIADB
    #    apt_repository:
    #      repo: deb [arch=amd64] https://mirror.docker.ru/mariadb/repo/10.6/ubuntu {{ ubuntu_name }} main
    #      filename: mariadb
    #      state: present
    #
    #  - name: MARIADB SRC
    #    apt_repository:
    #      repo: deb-src https://mirror.docker.ru/mariadb/repo/10.6/ubuntu {{ ubuntu_name }} main
    #      filename: mariadb
    #      state: present

    #  - name: VIRTUALBOX KEY
    #    apt_key:
    #      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    #      state: present
    #
    #  - name: VIRTUALBOX
    #    apt_repository:
    #      repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ubuntu_name }} contrib
    #      filename: virtualbox
    #      state: present

    - name: UPDATE CACHE
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: UPGRADE ALL PACKAGES
      apt:
        name: "*"
        state: latest

    - name: INSTALL PACKAGES BASICS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - gnupg-agent
          - lsb-release
          - vim
          - build-essential
          - checkinstall
          - make
          - automake
          - cmake
          - autoconf
          - dkms
          - git
          - dirmngr
          - software-properties-common
          - gcc
          - g++
        state: latest

    - name: UNINSTALL DEFAULT PACKAGES
      apt:
        name:
          - vim-tiny
          - xfburn
          - gnome-mines
          - gnome-sudoku
          - sgt-puzzles
          - simple-scan
          - pidgin
          - snapd
          - onboard
          - parole
        state: absent

    - name: UNINSTALL UNNECESSARY PACKAGES
      apt:
        autoremove: yes
